### PR TITLE
refactor: auto code refactor by sourcery (#1)

### PR DESCRIPTION
**Pull request by wizard-28**
Details: https://github.com/wizard-28/makedeb/pull/1

### CODE REVIEW

**Comment by hwittenborn** [comment]
I don't use Sourcery myself, and I don't plan on adding it to my tech stack for anything anytime soon.

I can see the issues it brought up, but I don't think I'd want to add Sourcery or anything to manage this all on every pull request.

Would there be any other tools that work like Sourcery (preferably one that can run completely on the client, like Black or Flake8)?

**Comment by wizard-28** [comment]
> I don't use Sourcery myself, and I don't plan on adding it to my tech stack for anything anytime soon.

> I can see the issues it brought up, but I don't think I'd want to add Sourcery or anything to manage this all on every pull request.

You don't have to though. I just made this PR as a one timer, it's your wish if you want to use Sourcery in the future.

This PR doesn't add Sourcery to your repository, it just fixes some code quality issues which Sourcery brought up.

> Would there be any other tools that work like Sourcery (preferably one that can run completely on the client, like Black or Flake8)?

I don't think so there is, Sourcery does automatic code refactoring for higher code quality. I haven't encountered any alternatives yet.

**Comment by hwittenborn** [comment]
You'll have to forgive me, I guess I overlooked something somewhere and thought Sourcery was being added in this PR :p

Would we be able to just do the f-string fix? I don't really use the .items() syntax for anything yet.

**Comment by wizard-28** [comment]
> You'll have to forgive me, I guess I overlooked something somewhere and thought Sourcery was being added in this PR :p

Sure :)

---

> Would we be able to just do the f-string fix? I don't really use the .items() syntax for anything yet.

Absolutely. I'm removing that change then.

**Comment by wizard-28** [comment]
@hwittenborn done.

**Pull request merged**
