### PR TITLE
Change DUR to MPR

### PR DESCRIPTION
**Pull request by Elsie19**
A small thing I noticed that was never changed since the DUR became the MPR.

### CODE REVIEW

**Comment by hwittenborn** [comment]
For the --dur-check things in the case statement for the arg check, could you preserve those alongside --mpr-check) for backwards compatibility? We'll still only mention --mpr-check in the help menu though.

**Review by hwittenborn — APPROVED** [review]
Lgtm :)

**Comment by hwittenborn** [comment]
While we're at it, can you go ahead and rename the `mpr_info.sh` file to `mpr_check.sh`? I must've changed the function name in the past without updating the filename itself :P

**Comment by Elsie19** [comment]
Remember to remove the backwards compatible dur check next 0.x.0 release

**Comment by hwittenborn** [comment]
Any reason to remove it? Is there any practical reason to besides the few extra lines of code?

**Comment by Elsie19** [comment]
Because your not the DUR anymore

**Comment by hwittenborn** [comment]
I suppose we could remove it at some point, but for the unbeknownst future I'd rather it stay, as it just breaks compatibility for something that isn't really hard to maintain.

Even if we do a major version bump, I still don't see that as a place where code cleanup at the sake of backwards compatibility has to be done - I know it's not identified as the DUR anymore, but again, I think it would help if we kept everything as-is for the sake of compatibility.

**Review by hwittenborn — APPROVED** [review]
Signing off one last time

**Pull request merged**
