### PR TITLE
Add support for conffiles via 'backup' variable

### LINKED ISSUE #107: Respect backup key in PKGBUILD
### Description of feature

Files output by makedeb do not respect the `backup` key, therefore files that should be protected from being overwritten during installation are not.

If makedeb could generate [conffiles](https://www.debian.org/doc/manuals/maint-guide/dother.en.html#conffiles) based on the `backup` key this would resolve this issue.

### Installed makedeb version

8.7.1-1

### PR DESCRIPTION
**Pull request by hwittenborn**
Closes #107.

### CODE REVIEW

**Review by hwittenborn — COMMENTED** [review]
Ready to merge

**Comment by hwittenborn** [comment]
Maybe not :p

**Comment by hwittenborn** [comment]
We good now

**Review by lpuv — COMMENTED** [review]
too late but lgtm

**Pull request merged**
